[feat, refactor] 홈 데이터 응답 시 데이터가 없는 모듈 생략, 이달의 무료 티켓 조회 로직 변경
teamesa/esa_backend pull request #246
Opened 2023-02-11 11:29 UTC by skullkim

- [X] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.`
- [X] 💯 테스트는 잘 통과했나요? 
- [X] 🏗️ 빌드는 성공했나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?

## 작업 내용
원래는 홈 데이터 응답 시 데이터가 없는 모듈을 생략하고 응답하는 기능만 구현하려 했으나, 구현 중 이달의 무료 티켓 조회 로직에 버그 존재와, 네이티브 쿼리를 통해 구현되 있다는 것을 알게 되었습니다. 따라서 모듈 응답에 대해 정확한 결과 기대를 위해선 해당 무분의 리팩터링이 선행되야 했습니다. 따라서 없는 데이터는 생략하는 기능을 구현함과 동시에 이달의 무료티켓 조회 로직을 변경했습니다.

일부 변동 파일에 대해 테스트가 존재하지 않습니다. 이는 한 PR이 너무 커짐에 따라 별도의 PR로 테스트를 추가하기로 결정했기 때문입니다. 해당 PR이 머지 된다면, 추가 PR로 부족한 테스트를 추가하겠습니다.
## 스크린샷
### 모듈 별로 데이터가 존재하지 않는다는 조건은 다음과 같습니다.
#### keyVisual
- API 형식:
```
{
    moduleName: "KEY_VISUAL",
    index: 0,
    data: {
        - keyVisualDatas: [{
            keyVisualPhotoUrl: string,
            upperTitle: string,
            lowerTitle: string | "",
            link: string | null
        },]
    }
}
```
- 데이터 유무 판단 기준: keyVisualDatas에 원소
  - 데이터가 없을 경우 keyVisualDatas의 size <= 0
  - 데이터가 있을 경우 keyVisualDatas의 size >= 1
### swipeItem
- API 형식:
```
{
    moduleName: "SWIPTE_ITEM",
    index: 1,
    data: {
        title: {
            text: string,
            link: string, // swipte item detail page url
        },
        context: {
            text: string,
            link: string, // swipte item detail page url
        },
        thunmbnailPhotoUrl: string,
        photoUrls: string[],
        keywords: string[]
    }
}
```
- 데이터 유무 판단 기준: title.text, context.text, thumbnailPhotoUrl, photoUrls, keywrods
  - 데이터가 없을 경우: 위 기준 중 하나라도 데이터가 없을 경우
  - 데이터가 있을 경우: 위 기준 데이터가 모두 존재할 경우
### monthlyFreeTicket
- API 형식:
{
	moduleName: "MONTHLY_FREE_ITEM",
	index: 4,
	data: {
		topTitle: string,
		bottomTitle: string,
		contents: [{
			id number,
			presentationImage: {
				url: string, // image s3 link
				link: string, //content detail page url
				backgroundText: null,
				dimColor: null,
				opacity: 0.
				dimTarget: boolean
			},
			typeBadge: {
				text: string,
				typeBadge: true
			},
			additionalBadgeList: [
				{
					text: string,
					typeBadge: boolean
				},
			],
			title: {
				text: string,
				link: string // content detail page url
			},
			heart: {
				heartClicked: boolean,
				link: string // heart click status update url
				id: number
			},
			listItemAdditionalInfo: {
				heartCount: number,
				grade: number,
				archiveCount: number
			}
		}, {...}]
	}
}
데이터 유무 판단 기준: contents
데이터가 없을 경우: contents의 size <= 0
데이터가 있을 경우: contents의 size >= 1
realTimeArchive
API 형식:
{
	moduleName: "REAL_TIME_ARCHIVE",
  index: number,
  data: {
		topTitle: string,
		bottomTitle: string,
	  archives: [{
	    photo: {
	      link: string,
        photoUrl: string,
      },
      metaData: {
	      user: {
	        name: string,
          photoUrl: string
        },
        heart : {
          heartClicked: boolean,
          link : string,
        },
        likeCount: number,
        starRating: number,
        updatedAt: string,
        dimColor: string,
        opacity: string
	    },
      introduction: {
	      title: {
	        link: string,
	        value: string,
	      }
	      places: string | "",
	      comment: string | ""
      }
	  },]
	}
}	
데이터 유무 판단 기준: archives
데이터가 없을 경우:  archives의 size <=0
데이터가 있을 경우: arvhies 의 size >= 1
## 주의사항

Closes #{이슈 번호}

2023-02-11 14:09 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/AdditionalBadgeListDto.java
> +public class AdditionalBadgeListDto {
이거 뭐에요?

2023-02-11 14:11 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ContentDto.java
> +public class ContentDto {
Content라는 게 너무 모호한 것 같아요. MonthlyFreeTicket을 붙이는 게 나을 것 같아요.

2023-02-11 14:12 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ContentDto.java
> +    static ContentDto from(MonthlyFreeTicketDto monthlyFreeTicketDto) {
not null이 안들어가는 거 보장 가능한가요?

2023-02-11 14:14 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +    public static final String OPACITY = "0";
1. Opacity는 0이 고정인가요?
2. 왜 퍼블릭인가요?
3. Default값인지 모르겠지만 오파시티라는 이름대신에 DEFAULT등의 의미를 부여한 이름이 더 좋을 것 같습니다

2023-02-11 14:21 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/ModuleHandler.java
> +    Optional<Object> generator(ModuleParamDto paramDto) throws RuntimeException;
이거 왜 Optional로 하셨을까요? 어떠한 장점이 있길래 쓰셨는지 궁금합니다.

2023-02-11 14:28 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private List<MonthlyFreeTicketDto> doesHeartedTicket(final List<MonthlyFreeTicketDto> monthlyFreeTicketDtos,
이거 해야지 나오나요? 안하면 어떻게 되나요?

2023-02-11 14:43 UTC, doho-ho requested changes
이달의 무료 티켓 조회 중점으로 봤습니다.
랜덤한 5개의 전시를 가져오는 요구사항은 제거하기로 논의된걸까요?
또 pick 유무 체크에 버그가 있네요 😢

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private List<MonthlyFreeTicketDto> doesHeartedTicket(final List<MonthlyFreeTicketDto> monthlyFreeTicketDtos,
이 메서드의 역할이 무엇인가요?

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                .limit(MAX_MONTLY_FREE_TICKETS)
native쿼리로 짠 이유가 기획 요구사항이 랜덤한 5가지를 뽑아오는 것이었는데요, limit 5로 단순히 5개만 가져오는건가요?

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private MonthlyFreeTicketDto isAuthenticatedUser(final MonthlyFreeTicketDto monthlyFreeTicketDto,
`isAuthenticatedUser`라면 인증된 사용자 유무를 판단하는 역할을 하는 메서드로 이해됩니다.
하지만 내용을 보면 `monthlyFreeTicketDto.userId`가 요청자와 같은지 판단해서 isHeart true, false 하는 것 같네요.

`monthlyFreeTicketDto.userId` 가 뭘 의미하나요?

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                            pick.pickedUser.id.as("userId"),
새로 추가된 것 같은데 무엇을 의미하나요?
item : pick = 1 : N 구조를 가지고 있습니다.

현재 쿼리를 보면 특정 아이템을 픽한 사람 중 제일 처음 조회되는 유저 아이디만 가져오는 것 같아요.

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                .on(pick.pickedItem.eq(itemEntity))
파라미터도 요청한 사용자 userId 입력 받고 on절을 아래와 같이 치환해주는 방법으로 해당 아이템을 pick 했는지 확인할 수 있을 것 같네요.
```java
.on(pick.pickedItem.eq(itemEntity), pick.pickedUser.id.eq(requestUserId))
```

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/MonthlyFreeTicketDto.java
> +    private Long userId;
이건 왜 필요한가요?

2023-02-11 14:43 UTC, doho-ho commented on kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandlerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
wildcard 사용하시는건가요?

2023-02-12 06:14 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/AdditionalBadgeListDto.java
> +public class AdditionalBadgeListDto {
코드 작성 도중 필요 없다는 것을 알고 안쓰게 되었는대 지우는 것을 잊었네요. 반영하겠습니다~

2023-02-12 06:16 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ContentDto.java
> +public class ContentDto {
네~

2023-02-12 06:25 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +    public static final String OPACITY = "0";
1. 네~
2. 실수했네요. private으로 바꿀게요.
3. 그럼 DEFAULT_OPACITY로 바꿀게요~

2023-02-12 06:38 UTC, chanhl22 commented on kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ContentDtoTest.java
> +    @DisplayName("ContentDto 인스턴스를 새성한다.")
오타가 있어요

2023-02-12 06:46 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/ModuleHandler.java
> +    Optional<Object> generator(ModuleParamDto paramDto) throws RuntimeException;
#241 에서 쓰여있는 대로, 데이터가 존재하지 않는 데이터를 응답으로 돌려주지 않아야 하는 대요. 결론 부터 말하면 이 방식이 가장 최선이라 생각했기 때문이에요. 
각 모듈 별로 "데이터가 존재하지 않는다"에 대한 상세한 기준을 설정 하고, 각 모듈 별로 그에 맞는 로직을 작성하기 위해선 각 모듈을 담당하는 ModuleHandler의 generator()에서 하는게 맞겠다는 생각을 했어요. 그 후, 내부 로직을 어떻게 작성할지를 고민했어요. 그 결과 세 가지 방안이 떠올랐어요.
1. 데이터가 존재하지 않으면 예외를 던진다.
2. 데이터가 존재하지 않으면 NULL을 던진다
3. Optional로 반환값을 설정한다.

이제 각 경우의 수에 대해 장단점을 말해 볼게요.
1. 데이터가 존재하지 않으면 예외를 던진다.
- 이 방법을 사용하면 generator()를 호출하는 곳에서 데이터 유무를 검증하지 않아도 되니 코드가 보다 간결할 것이라는 생각을 했어요. 하지만 불필요한 에러를 사용하면, 실제 에러 발생 상황과 구별을 할 수 없게 되요. 이 경우 데이터가 없는게 예외를 터트릴 상황이 아니라는 생각을 해서 1번은 배제했어요. 이 논리를 뒷바침하는 글이 있는대요. [이펙티브 자바 Item.69 예외는 진짜 예외 상황에서만 사용하라.](https://www.skullkim-dev.com/2022/04/17/Item-69.-%EC%98%88%EC%99%B8%EB%8A%94-%EC%A7%84%EC%A7%9C-%EC%98%88%EC%99%B8-%EC%83%81%ED%99%A9%EC%97%90%EB%A7%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC/)를 참고해 주세요.
2. 데이터가 존재하지 않으면 NULL을 던진다.
- 아주 전통적인 방법이죠. 하지만 NULL은 의미가 명확하지 않아요. 이 값 자체가 NULL이여도 되는지, 아니면 어떤 문제가 있는 건지도 알 수 없죠. 또 한, NullPointerException에서도 자유롭지 않죠. 더 상세한 NULL의 단점은 [모던 자바 인 액셩 11장. null 대신 Optional 클래스](https://www.skullkim-dev.com/2022/03/27/11%EC%9E%A5.-null-%EB%8C%80%EC%8B%A0-Optional-%ED%81%B4%EB%9E%98%EC%8A%A4/)를 참고해 주시면 좋을 거 같아요.
3. Optional로 반환값을 설정한다.
- Optional 자체가 반환값의 존재 유무를 명확하게 나타내기 위해 도입되었죠. 따라서 위에서 언급한 NULL의 단점을 커버해줘요. 따라서 이 방식이 가장 깔끔한 방식이라 생각해 사용했습니다.

2023-02-12 06:50 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private List<MonthlyFreeTicketDto> doesHeartedTicket(final List<MonthlyFreeTicketDto> monthlyFreeTicketDtos,
이 달의 무료 티켓 UI를 보면 다음과 같이 우측 상단에 픽을 할 수 있는 하트 이모지가 존재해요.
<img width="465" alt="스크린샷 2023-02-12 오후 3 47 28" src="https://user-images.githubusercontent.com/37966705/218297211-e95f9c9d-bcc0-4871-9f42-62a59c88fb8f.png">
이 하트는 로그인이 되어 있다면, 픽 여부에 따라 표시를 해줘야 하죠. 만약 픽을 하지 않았다면 무조건 픽을 하지 않았다고 표시해 줘야 하죠. 그래서 로그인 여부에 따라 값을 변환해 반환하기 위해 위와 같은 로직을 넣었어요/.

2023-02-12 06:52 UTC, skullkim commented on kilometer-backend-api/src/test/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ContentDtoTest.java
> +    @DisplayName("ContentDto 인스턴스를 새성한다.")
감사합니다~

2023-02-14 05:04 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/ContentDto.java
> +    static ContentDto from(MonthlyFreeTicketDto monthlyFreeTicketDto) {
외부에서 null을 인자로 넣으면 null이 들어가겠죠? 하지만, 이렇게 생각한다면 모든 파라미터에는 다 null이 들어갈 수 있는 거 아닌가요? 이 메서드에서만 not null이 보장되는지를 물어본 이유가 있을까요?

2023-02-14 05:05 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private List<MonthlyFreeTicketDto> doesHeartedTicket(final List<MonthlyFreeTicketDto> monthlyFreeTicketDtos,
[답변](https://github.com/teamesa/kilometer_backend/pull/246#discussion_r1103745618) 참고해 주세요~

2023-02-14 05:08 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                .on(pick.pickedItem.eq(itemEntity))
감사합니다~

2023-02-14 05:20 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private MonthlyFreeTicketDto isAuthenticatedUser(final MonthlyFreeTicketDto monthlyFreeTicketDto,
monthlyFreeTicketDto의 userId는 픽을 한 유저의 id를 의미해요~. 이 id와 accessToken에서 가져온 userId를 비교해서 로그인 여부를 판단해요.

2023-02-14 05:21 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                            pick.pickedUser.id.as("userId"),
[이 방식](https://github.com/teamesa/kilometer_backend/pull/246#discussion_r1103638813)을 사용하면서 해당 부분은 더 이상 필요하지 않게 됐어요.

2023-02-14 05:21 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/MonthlyFreeTicketDto.java
> +    private Long userId;
[이 용도](https://github.com/teamesa/kilometer_backend/pull/246#discussion_r1105305261)로 사용했는대요. 로직 바꾸면서 사용하지 않게 되었어요~

2023-02-14 05:22 UTC, skullkim commented on kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandlerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
네~

2023-02-14 07:37 UTC, gudonghee2000 approved these changes
안녕하세요 윤기님! 작성해주신 코드 모두 잘보았습니다!😊
몇가지 궁금한 부분과 의견을 제시해보았어요!
답변 달아주시면 바로 확인하겠습니다~
정말 고생하셧습니다!!

2023-02-14 07:37 UTC, gudonghee2000 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
`id`가 어떤 테이블의 레코드에 대한 `id` 인지 명시되면 더좋을것 같아요~

2023-02-14 07:37 UTC, gudonghee2000 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +
다른 dto와 다르게 `PresenatationImageDto`는 필드를 final로 지정해주시지 않은 이유가 있으신건가요??

2023-02-14 07:37 UTC, gudonghee2000 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                            itemEntity.id.as("itemId"),
윤기님! 해당 부분이 `item`과 연관된 테이블들을 가져오는 쿼리인가요??
만약 그렇다면 쿼리 dsl로 쿼리를 한번에 날리는 것이 아닌 
`item` Entity만을 랜덤하게 다섯개 가져오고 필요한 부분은 `item` 엔티티에서 내부에서 지연로딩을 사용해서 값을 만드는 것은 불가능하거나 성능적으로 문제가 있는건가요??

2023-02-14 07:40 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
heartDto에 있는 id이니 heart의 id라는 것을 알 수 있지 않을까요? 통상적으로 래퍼 클래스를 만들었을 때 필드를 value같은 단어로 칭하죠. 예를 들어 Name이라는 래퍼 클래스의 필드를 value라고 하죠. 이는 명시적인 이름을 사용함과 동시에 불필요한 단어 의미상의 중복을 막기 위해서인대요. HeartDto에서 id가 아닌 heartId라고 한다면, 이 역시 중복 아닐까요?

2023-02-14 07:47 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                            itemEntity.id.as("itemId"),
```
 @OneToOne(mappedBy = "item", fetch = FetchType.LAZY)
    private ItemDetail itemDetail;

    @OneToMany(mappedBy = "item", fetch = FetchType.LAZY)
    @Builder.Default
    private List<ItemDetailImage> itemDetailImages = new ArrayList<>();
```
위 코드가 ItemEntity에서 연관관계를 매핑한 부분인대요. 여기에 archive와 pick의 연관관계는 존재하지 않아요. 그리고 가져오는 조건이 다음과 같이 두 개의 테이블에 각자 존재하는 컬럼을 봐야 해서 item 엔티티를 랜덤하게 다섯개 가져오면 이 다섯개를 다 사용할 수 있을거라는 보장이 없지 않을까요?
findTopRandomFiveMonthlyFreeTicket()의 where 절은 다음과 같아요
```
  .where(
                        itemEntity.feeType.eq(FeeType.FREE),
                        itemEntity.exposureType.eq(ExposureType.ON),
                        itemEntity.startDate.loe(now).and(itemEntity.endDate.gt(now)),
                        archive.isVisibleAtItem.isTrue()
                )
```

2023-02-14 07:54 UTC, gudonghee2000 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
flyway 관련 스키마를 보면 `heart` 라는 테이블이 보이지 않는데, `hearId` 라는 필드가 있는건가요??
말씀해주신 부분에서 `heart` 테이블로 데이터를 가져온것이라면 `HeartDto에서 id가 아닌 heartId라고 한다면, 이 역시 중복 아닌가` 하는 부분에 동의해요😊 
예를들어 일급컬렉션의 필드를 `values` 표현하는 것과 일치한다고 생각해요.

하지만 `heart` 테이블이 아닌 다른 테이블로 부터 가져온 `id` 필드라면 해당 테이블에 대한 명시가 있는것이 `heartDto`의 `id` 칼럼에 있는것이 좋지 않을까요??
`heart` 테이블에서 가져온 `id`라면 윤기님 의견에 적극동의합니다!

2023-02-14 08:00 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +
null일 수도 있는 필드가 존재해서 그래요~

2023-02-14 08:02 UTC, gudonghee2000 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                            itemEntity.id.as("itemId"),
`item에 archive와 pick의 연관관계는 존재하지 않음` 이부분은 `Archive`와 `Pick`이 이미 다대일 단방향 매핑으로 `item`을 알고 있기 때문에 다대일 양방향 매핑을 활용하는 방법도 좋을 것 같아요!

하지만 위에 말씀해주신 `where 조건 절`은 어플리케이션에서 처리한다면 성능 이슈가 있을수 있기때문에 쿼리로 처리하는 것이 더 적절할 것같다는 생각이 들어요!
대신 `item` 엔티티가 5개의 테이블들을 양방향 매핑으로 알게 되면 쿼리로 처리하거나 dto로 값을 매핑해서 가져오는 부분들을 Entity의 비지니스 로직으로 추상화하여 숨겨줄 수 있을 것 같다는 생각이 들어요.
이부분은 시간이 많이 걸릴 것 같아 나중에 고민해보아도 좋을것 같네요!

2023-02-14 08:09 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
사실 이거는 도메인용어 불일치로 인해 발생한 문제에요. 백엔드에서는 pick이라 하지만 프론트에서는 heart라는 용어를 사용하고 있어요. 그리고 이 부분은 기존 API를 그대로 따라가면서 API 모듈을 통한 요청이 들어왔을 때만 응답에 추가되는 부분을 분리시킨 로직이에요. 그래서 이 문제는 도메인 용어를 일치시키는 것으로 해결해야 할거 같네요.

2023-02-14 08:13 UTC, gudonghee2000 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +
그렇군요~

2023-02-14 08:15 UTC, gudonghee2000 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
그렇군요! 이 부분은 나중에 프론트와 백엔드가 도메인 용어를 일치시켜야겠네요!
이부분은 제가 노션에 ISSUE로 등록해놓겠습니다😊

2023-02-15 15:22 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/ModuleHandler.java
> +    Optional<Object> generator(ModuleParamDto paramDto) throws RuntimeException;
완전 좋아용~ 잘 설명해주셨습니당. 저도 1번은 제외고 사실 2,3번이 주요할 것 같아요.
사실 이 질문의 주목적은 뒤의 코드였어요. 
이 메소드를 호출하는 쪽은 전통적인 for-each 방식으로 객체를 하나하나 생성하는데 반해, Optional은 함수형에서 많이 쓰는 모나드를 Nullable함을 감추기 위해서 사용되었다고 생각합니당. 
Optional을 쓴다면 호출하는 쪽을 바꾸는게 좋지 않을까 생각이 되구요.

그리고 무조건 Optional을 쓰면 결국 혼선만 야기하고 Optional 자체도 객체이기에 Optional 대신에 null을 반환해도 같거든요.
오히려 한단계 래핑만 되어있는 상태라 생각이 되어, 가독성을 해칠수 있다고 생각이 들어요~
장단점 분석 좋지만 3번도 단점이 있다는 것은 명심해주셨으면 좋겠습니다~

2023-02-15 15:25 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
굳이 동일시 되어야할까요? 왜 프론트가 백의 용어에 좌지우지 당해야하는건지 모르겠어요. 프론트는 pick이던 like던 동일한 포맷을 가집니다.

2023-02-15 15:26 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +
저 이거 궁금한게 왜 nullable이 final과 관계가 있나요?

2023-02-15 15:27 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandler.java
> +    private List<MonthlyFreeTicketDto> doesHeartedTicket(final List<MonthlyFreeTicketDto> monthlyFreeTicketDtos,
네 이건 사실 동호님이 설명해주신 부분을 말하고 싶었어요 굳이 한번더 래핑할 필요없습니다.

2023-02-15 15:29 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                .orderBy(Expressions.numberTemplate(Long.class, "function('rand')").asc())
오홍 이러면 되나용?

2023-02-15 15:30 UTC, azxca1731 commented on kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandlerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
빼주세요~ wildcard~ 불필요한거 들어갈 수 있습니당.

2023-02-16 06:15 UTC, skullkim commented on kilometer-backend-domain/src/test/java/com/kilometer/domain/homeModules/modules/monthlyFreeTicket/MonthlyFreeItemHandlerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
네~

2023-02-16 06:18 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/HeartDto.java
> +        return HeartDto.builder()
하나의 대상을 가르킬 때 서로 다른 용어를 사용한다면 의사소통에 더 많은 비용을 지불하게 되지 않을까요? 또 한, 개발을 하거나 문서를 작성함에 있어서 대상이 같아도 상황에 맞는 용어를 생각해야 하니 잘못된 용어를 사용할 가능성도 커지고요. 용어를 통일하는 것은 특정 대상이 다른 하나의 대상에 의해 좌지우지 되는 것이 아닌, 의사소통의 원활함에 있어서 반드시 필요하다고 생각해요.

2023-02-16 06:19 UTC, skullkim commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemRepositoryCustomImpl.java
> +                .orderBy(Expressions.numberTemplate(Long.class, "function('rand')").asc())
네~. 기술 블로그에 포스팅 해두었어요

2023-02-16 06:25 UTC, skullkim commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/dto/module/monthlyfreeticket/PresentationImageDto.java
> +
final로 지정하면 생성자에서 무조건 할당을 해줘야 해서 final을 사용하지 않았아요. 디폴트 값으로 null이 들어가기 때문에 명시적으로 null을 넣지 않아도 되죠. 또 한, dto에서 null이어도 되는 곳에 final을 사용하지 않으면 코드상 더 쉽게 null 가능 여부를 알 수 있지 않을까요?

2023-02-16 07:15 UTC, doho-ho approved these changes

2023-02-17 00:22 UTC, merged